GET http://localhost:3000/quotes

###

GET http://localhost:3005/subscribers/6386c23bd8d550d5056d9f58

###

POST http://localhost:3000/api/quotes
Content-Type: application/json

{
    "quote": "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "source": "Winston Churchill",
    "year": 1965
}

###

DELETE http://localhost:3005/quotes/6386cebd8e46d54b629c1bce

###

PATCH http://localhost:3005/quotes/638698b0c83d71af157b499c
Content-Type: application/json

{
    "source": "New name"
}