GET http://localhost:3000/quotes

###

GET http://localhost:3000/6386d168770eb35c785138db

###

POST http://localhost:3000/quotes
Content-Type: application/json

{
    "quote": "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    "source": "Winston Churchill",
    "year": 1965
}

###

DELETE http://localhost:3000/quotes/6386d1ea770eb35c785138e3

###

PATCH http://localhost:3005/quotes/638698b0c83d71af157b499c
Content-Type: application/json

{
    "source": "New name"
}